---
title: "TidyTuesday - gov spending on kids"
author: "wjtorres"
date: '2020-09-15'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(viridis)
library(hrbrthemes)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2020-09-15")

```

# Readme

```{r Readme, eval = interactive()}

tt

```

# Create Data Frame

```{r Glimpse}

kids <- tt$kids

```


```{r}
# check variable levels
unique(kids$variable)

#"PK12ed","highered", "edsubs", "edservs", "pell", "HeadStartPriv", "TANFbasic","othercashserv","SNAP","socsec","fedSSI","fedEITC",
# "CTC","addCC", "stateEITC", "unemp", "wcomp", "Medicaid_CHIP", "pubhealth","other_health", "HCD", "lib", "parkrec


# factor collapse

kids$variable2 <- fct_collapse(kids$variable,
  education = c("PK12ed", "highered", "edsubs", "edservs", "pell", "HeadStartPriv"),
  payments = c("TANFbasic", "othercashserv", "SNAP", "socsec", "fedSSI", "fedEITC"),
  tax = c("CTC", "addCC", "stateEITC"),
  employ = c("unemp", "wcomp"),
  health = c("Medicaid_CHIP" ,"pubhealth", "other_health"),
  community = c("HCD", "lib", "parkrec"))

# create df

kids_total <- kids %>%
  group_by(variable2, year) %>%
  summarise(inf_adj_total = sum(inf_adj, na.rm = T))
```


```{r}
# create plot

kids_total %>%
  ggplot(aes(x = year, y = inf_adj_total, fill = variable2)) +
  geom_area(colour = "black", size = .2, alpha = .8) +
  scale_x_continuous(breaks = seq(1997, 2016, 1)) +
  scale_y_continuous(labels = scales::comma) +
  theme_ipsum() +
  scale_fill_viridis(discrete = T, "Spending Area",
    limits = c("tax",
               "education",
               "payments",
               "community",
               "health",
               "employ"),
    labels = c("Tax Credits",
               "Education",
               "Cash Assistance, SSI",
               "Housing, Libraries, Parks, Rec",
               "Medicaid, Health",
               "Unemployment")) +
  theme(legend.position="bottom") +
  labs(
    title = "Total US Spending on Kids (1997-2016)",
    x = "Year", 
    y = "Total US Spending",
    caption = "source = Urban Institute, courtesy of Joshua Rosenberg's r package - tidykids \n graph by @wjtorres"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))




```
