---
title: "TidyTuesday - datasauRus dozen"
author: "wjtorres"
date: '2020-10-13'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2020-10-13")

```

# Pull Data

```{r Glimpse}

datasaurus <- tt$datasaurus

```


# Wrangle

```{r}
datasaurus2 <- datasaurus %>%
  group_by(dataset) %>%
  mutate(x_mean = mean(x),
         y_mean = mean(y))
```

# Visualize

```{r Visualize, fig.width = 12, fig.height = 8}

datasaurus2 %>%
  ggplot(aes(x, y, color = x)) +
  geom_point(size = 1, alpha = .8) +
  geom_smooth(method = "lm", se = FALSE, color = "snow1") +
  geom_point(aes(x_mean, y_mean),
             shape = 15, color = "#e9c46a", size = 3) +
  facet_wrap( ~dataset) +
  labs(
    title = "DatasauRus Dozen",
    subtitle = "Each with similar summary statistics (e.g., trend line and mean shown)",
    x = NULL,
    y = NULL,
    caption = "source =  datasauRus R package \ngraph by @wjtorres"
  ) +
   scale_colour_viridis_c(option = "D") +
  theme_minimal() +
  theme(
    legend.position = 'none',
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_text(color = "white", size = 11),
    plot.caption = element_text(color = "white", size = 11),
    plot.title = element_text(color = "white", size = 20),
    plot.subtitle = element_text(color = "white", size = 11),
    strip.text.x = element_text(color = "white", size = 11),
    plot.background = element_rect(fill = "#111111"))

  
```

# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
# ggsave(
  # filename = "My TidyTuesday Plot.png",
  # device = "png")

```
