---
title: "TidyTemplate"
author: wjtorres
date: 2021-01-12
output: html_output
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales) # for commas in axis
library(showtext) # for adding google font
library(ragg) # for agg_png function; draw to a PNG file

# open showtext
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-01-12")

```

# Pull Data

```{r Pull Data}

artwork <- tt$artwork
```


# Wrangle

```{r Wrangle}

width_outliers <- sort(boxplot.stats(artwork$width)$out) # width of 686 mm is smallest outlier

height_outliers <- sort(boxplot.stats(artwork$height)$out) # height of 723 mm is smallest outlier

artwork2 <- artwork %>%
  mutate(
    acquisitionYearGroups = case_when(
    acquisitionYear >= 1823 & acquisitionYear < 1830 ~ "1820s",
    acquisitionYear >= 1830 & acquisitionYear < 1840 ~ "1830s",
    acquisitionYear >= 1840 & acquisitionYear < 1850 ~ "1840s",
    acquisitionYear >= 1850 & acquisitionYear < 1860 ~ "1850s",
    acquisitionYear >= 1860 & acquisitionYear < 1870 ~ "1860s",
    acquisitionYear >= 1870 & acquisitionYear < 1880 ~ "1870s",
    acquisitionYear >= 1880 & acquisitionYear < 1890 ~ "1880s",
    acquisitionYear >= 1890 & acquisitionYear < 1900 ~ "1890s",
    acquisitionYear >= 1900 & acquisitionYear < 1910 ~ "1900s",
    acquisitionYear >= 1910 & acquisitionYear < 1920 ~ "1910s",
    acquisitionYear >= 1920 & acquisitionYear < 1930 ~ "1920s",
    acquisitionYear >= 1930 & acquisitionYear < 1940 ~ "1930s",
    acquisitionYear >= 1940 & acquisitionYear < 1950 ~ "1940s",
    acquisitionYear >= 1950 & acquisitionYear < 1960 ~ "1950s",
    acquisitionYear >= 1960 & acquisitionYear < 1970 ~ "1960s",
    acquisitionYear >= 1970 & acquisitionYear < 1980 ~ "1970s",
    acquisitionYear >= 1980 & acquisitionYear < 1990 ~ "1980s",
    acquisitionYear >= 1990 & acquisitionYear < 2000 ~ "1990s",
    acquisitionYear >= 2000 & acquisitionYear < 2010 ~ "2000s",
    acquisitionYear >= 2010 & acquisitionYear < 2020 ~ "2010s"),
    outlier = case_when(
      height >= 723 | width >= 686 ~ 1,
      TRUE ~ 0)) %>%
  relocate(acquisitionYear, .after = acquisitionYearGroups) %>%
  filter(!is.na(acquisitionYear))

artwork2 %>%
  count(acquisitionYearGroups)

  
```

# Prep additional dataframes for visualizations

```{r}

# create locations in the facet for text
title_1820s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1820s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1830s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1830s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1840s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1840s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1850s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1850s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1860s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1860s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1870s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1870s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1880s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1880s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1890s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1890s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1900s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1900s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1910s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1910s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1920s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1920s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1930s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1930s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1940s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1940s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1950s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1950s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1960s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1960s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1970s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1970s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1980s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1980s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_1990s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("1990s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_2000s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("2000s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )

title_2010s <- data.frame(
  width = 11500, 
  height = 34000,
  acquisitionYearGroups = factor("2010s", levels = c("1820s", "1830s", "1840s", "1850s","1860s", "1870s", "1880s", "1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))
  )
```


# Visualize 

```{r Visualize}

# add google fonts
font_add_google(name = "Lustria", family = "one")
font_add_google(name = "Open Sans", family = "two")

# save my colors
orange <- "#FFA500"
l_grey <- "#a6a6a6"
d_grey <- "#222222"
l_blue <- "#e5eeff"
d_blue <- "#ccdeff"
l_purple <- "#f6e5ff"
d_purple <- "#edccff"

# create my theme
my_theme <- theme(
  
  # title
  plot.title = element_text(family = "one", size = 16, hjust = 0, color = l_grey, margin = margin(10, 0, 0, 0)),
  
  # subtitle
  plot.subtitle = element_text(family = "one", size = 12, hjust = 0, color = orange, margin = margin(0, 0, 0, 0)),
  
  # caption
  plot.caption = element_text(family = "one", size = 6, hjust = 0, color = l_grey),
  
  # axis
  axis.text = element_text(family = "one", size = 6, color = l_grey),
  axis.title = element_text(family = "one", size = 6, color = l_grey),
  axis.ticks = element_blank(),
  
  # strip background
  strip.background = element_blank(),
  strip.text.x = element_blank(),
  
  # facet panel spacing
  panel.spacing=unit(0, "lines"),
  
  # facet panel
  panel.border = element_rect(color = l_grey, fill = NA),
  
  # plot background
  panel.background = element_rect(color = l_grey, linetype = "solid"),
  plot.background = element_rect(fill = "snow")
)

# create plot
my_plot <- artwork2 %>%
  
  ggplot(aes(x = width, y = height, group = acquisitionYearGroups)) +
  
  # add geom_rect for diff color quadrants
  geom_rect(
    xmin = 0,
    xmax = 6000,
    ymin = 0,
    ymax = 20000,
    alpha = .2,
    fill = l_blue,
    color = l_blue
  ) +
  
  geom_rect(
    xmin = 6000,
    xmax = 12000,
    ymin = 0,
    ymax = 20000,
    alpha = .2,
    fill = l_purple,
    color = l_purple
  ) +
  
  geom_rect(
    xmin = 0,
    xmax = 60000,
    ymin = 20000,
    ymax = 40000,
    alpha = .2,
    fill = d_blue,
    color = d_blue
  ) +
  
  geom_rect(
    xmin = 6000,
    xmax = 12000,
    ymin = 20000,
    ymax = 40000,
    alpha = .2,
    fill = d_purple,
    color = d_purple
  ) +
  
  # points
  geom_point(aes(color = as.factor(outlier)), alpha = .3, size = 3) +
  
  # facet wrap
  facet_wrap(vars(acquisitionYearGroups), ncol = 5) +
  
  # scales
  scale_color_manual(values=c(d_grey, orange), guide = FALSE) +
  scale_y_continuous(limits = c(0, 40000), breaks = c(0, 20000), expand = c(0, 0), labels = comma) +
  scale_x_continuous(limits = c(0, 12000), breaks = c(0, 6000), expand = c(0, 0), labels = comma) +
  
  # add category text labels
  geom_text(data = title_1820s, aes(x = width, y = height), label = "1820s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1830s, aes(x = width, y = height), label = "1830s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1840s, aes(x = width, y = height), label = "1840s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1850s, aes(x = width, y = height), label = "1850s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1860s, aes(x = width, y = height), label = "1860s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1870s, aes(x = width, y = height), label = "1870s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1880s, aes(x = width, y = height), label = "1880s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1890s, aes(x = width, y = height), label = "1890s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1900s, aes(x = width, y = height), label = "1900s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1910s, aes(x = width, y = height), label = "1910s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1920s, aes(x = width, y = height), label = "1920s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1930s, aes(x = width, y = height), label = "1930s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1940s, aes(x = width, y = height), label = "1940s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1950s, aes(x = width, y = height), label = "1950s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1960s, aes(x = width, y = height), label = "1960s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1970s, aes(x = width, y = height), label = "1970s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_1980s, aes(x = width, y = height), label = "1980s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_1990s, aes(x = width, y = height), label = "1990s",
            size = 4, color = l_grey, hjust = 1, family = "one") +
  
  geom_text(data = title_2000s, aes(x = width, y = height), label = "2000s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  geom_text(data = title_2010s, aes(x = width, y = height), label = "2010s",
            size = 4, color = l_grey, hjust = 1, family = "one") +

  #labs
  labs(title = "THROUGH THE DECADES: ARTWORK OWNED BY THE TATE ART MUSEUM",
       subtitle = "OUTLIERS IN ORANGE",
        # subtitle = "<span style = 'color: orange;'><b>OUTLIERS IN ORANGE</b></span>",
       # subtitle = "ARTWORK WITH WIDTH OR HEIGHT AS OUTLIER SHOWN IN <span style = 'color: orange;'><b>ORANGE</b></span>",
       caption = "DESIGN: JACKIE TORRES | SOURCE: TATE COLLECTION | #TIDYTUESDAY 2021W3",
       x = "WIDTH (IN MM)",
       y = "HEIGHT (IN MM)") +
  
  #use my theme
  my_theme

my_plot

# save image
ggsave("my_plot.png",
       plot = my_plot,
       device = agg_png(width = 9, height = 5, units = "in", res = 300))

dev.off()




```

