---
title: "TidyTuesday - IKEA"
author: "wjtorres"
date: '2020-11-03'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
```

# Load the weekly Data

```{r Load}

tt <- tt_load("2020-11-03")

```

# Pull data

```{r Readme, eval = interactive()}

ikea <- tt$ikea

```

# Wrangle and Visualize

```{r Wrangle}
ikea %>%
  mutate(USD_price = .27 * price) %>% # convert to USD
  group_by(category) %>%
  summarize(mean_USD_price = mean(USD_price)) %>% #average price
  ggplot(aes(x = reorder(category, mean_USD_price), y = mean_USD_price)) +
  geom_bar(stat = "identity", fill = "#FFDA1A", color = "#000000") +
  geom_text(aes(label = paste0("$", round(mean_USD_price, 1))), color="#0051BA", size = 3.5, hjust = 1.1) + # for the label, add a dollar sign and round to one decimal
  scale_y_continuous(labels = dollar_format()) + # using scales package, use a dollar format for the y axis
  labs(
    title = "IKEA Items",
    x = NULL,
    y = "Average Price, USD") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_text(color = "white", size = 10),
    axis.title = element_text(color = "white", size = 10),
    plot.caption = element_text(color = "white", size = 10),
    plot.title = element_text(color = "white", size = 14),
    plot.background = element_rect(fill = "#0051BA")) +
  coord_flip()

```


# Save Image

```{r}

# This will save your most recent plot
# ggsave(
#   filename = "My TidyTuesday Plot.png",
#   device = "png")

```
