---
title: "TidyTuesday - Chopped"
author: "wjtorres"
date: '2020-09-08'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


```{r setup}

library(tidyverse)
library(tidytuesdayR)
library(ggthemes)

```

# Get data

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-09-08')

friends_info <- tuesdata$friends_info

```


# Wrangle Data

```{r}
friends_info$imdb_rating_group <- cut(
  friends_info$imdb_rating,
  breaks = quantile(friends_info$imdb_rating, c(0, 0.25, 0.5, 0.75, 1)),
  labels = c("7.2 to 8.1", "8.2 to 8.3", "8.4 to 8.6", "8.7 to 9.7"),
  right  = FALSE,
  include.lowest = TRUE
)
```

# Plot Data

```{r}
friends_info %>%
  ggplot(aes(x = as.factor(season), y = as.factor(episode), fill = imdb_rating_group)) +
  geom_tile() +
  labs(
    title = "IMDB Ratings for Every Episode of Friends",
    subtitle = "(10 Seasons, 236 Episodes)",
    x = "Season #",
    y = "Episode #",
    fill = "Rating",
    caption = "source: friends R package \n graph by @wjtorres"
  ) +
  scale_fill_brewer(palette = "BuPu") +
  theme_few()

```

