---
title: "TidyTemplate"
date: 2021-02-09
author: wjtorres
output: html_output
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales) # for dollar format

library(showtext) # for adding google fonts
library(ragg) # for agg_png function; draw to a PNG file

# open showtext
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-02-09")

```

# Pull Data

```{r Glimpse}

retirement <- tt$retirement

```

# Wrangle

```{r Wrangle}

# create a new df and select only Black families and white families
retirement2 <- retirement %>%
  filter(race %in% c("White","Black"))

# create a new df for line segments (disparity marker); will also be used for ribbon area
line_segments <- retirement2 %>%
  pivot_wider(names_from = race, values_from = retirement)

# create dfs that will serve to label disparity amounts
text_1989 <- line_segments %>%
  mutate(label = White - Black) %>%
  mutate(position = 19000) %>%
  filter(year == 1989)

text_2016 <- line_segments %>%
  mutate(label = White - Black) %>%
  mutate(position = 90000) %>%
  filter(year == 2016)


```


# Visualize

```{r Visualize}

# add google fonts
font_add_google(name = "Merriweather", family = "one")
font_add_google(name = "Nanum Gothic", family = "two")

# my colors
d_grey <- "#383838"
d_blue <- "#0b5da7"
white <- "#f9fafc"

# my theme
my_theme <- theme(
  
   # title
  plot.title = element_text(family = "one", size = 14, hjust = 0, color = d_grey, margin = margin(10, 0, 0, 0)),
  
  # subtitle
  plot.subtitle = element_text(family = "two", size = 10, hjust = 0, color = d_grey, margin = margin(0, 0, 10, 0)),
  
  # caption
  plot.caption = element_text(family = "two", size = 6, hjust = 0, color = d_grey, margin = margin(10, 0, 0, 0)),
  
  # panel background
  plot.background = element_rect(fill = white),
  panel.background = element_rect(fill = white),
  
  # remove grid
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(),
  
  # axis
  axis.title.y = element_text(family = "two", size = 6, color = d_grey),
  axis.text = element_text(family = "two", size = 6, color = d_grey),
  
  # axis line
  axis.line = element_line(color = d_grey),

  # remove y axis text and ticks
  axis.ticks.y = element_blank(),
  axis.ticks.x = element_blank(),
)

# my plot
my_plot <- 
  
  ggplot() +

  # add lines
  geom_line(data = retirement2, aes(x = year, y = retirement, group = race, color = race), show.legend = FALSE) +
  
  # add ribbon to fill in area
  geom_ribbon(data = line_segments, aes(x = year, ymin = Black, ymax = White), fill = d_blue, alpha = 0.5) +
  
  # add segment lines (disparity markers)
  geom_segment(data = line_segments, 
               aes(x = year,
                   xend = year,
                   y = White,
                   yend = Black),
               linetype = "dotted",
               color = d_blue) +
  
  # add disparity amount labels
  geom_label(data = text_1989,
             aes(x = year,
                 y = position,
                 label = dollar(round(label, 0))), color = white, fill = d_blue, size = 2.5) +
  
  geom_label(data = text_2016,
             aes(x = year,
                 y = position,
                 label = dollar(round(label, 0))), color = white, fill = d_blue, size = 2.5) +
  
  # add family labels to lines
  annotate("text", x = 2016.1, y = 157884.20, label = "white families", family = "two", color = d_grey, size = 2.5, hjust = 0, vjust = .5) +
  annotate("text", x = 2016.1, y = 25211.850, label = "Black families", family = "two", color = d_grey, size = 2.5, hjust = 0, vjust = .5) +
  
  # scales
  scale_x_continuous(breaks = seq(1989, 2016, 3), limits = c(1988, 2018)) +
  scale_y_continuous(labels = dollar) +
  scale_color_manual(values = c("White" = d_blue, "Black" = d_blue)) +

  # labs
  labs(
    title = "Increasing disparity in family liquid retirement savings",
    subtitle = "In 1989, white families had $26,695 more in average liquid retirement savings than Black \nfamilies. By 2016, the disparity in savings grew to $132,672, representing a fivefold increase \nin disparity.",
    caption = "Design: Jackie Torres | Source: Urban Institute & US Census | #TidyTuesday 2021W7",
    x = NULL,
    y = "Average liquid retirement savings"
  ) +
  
  # use my theme
  my_theme

# print my plot
my_plot

# save image
ggsave("my_plot.png",
       plot = my_plot,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
dev.off()
  
```
