---
title: "TidyTuesday"
date: 2020-08-11
output: html_output
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(ggthemes) # for pander theme

```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2020-08-11")

```

# Pull Dataframe

```{r}

avatar <- tt$avatar

```

# Wrangle
```{r Wrangle}

speaking <- avatar %>%
  filter(character != "Scene Description") %>%
  select(book, book_num, chapter, chapter_num, character, character_words) %>%
  group_by(book, book_num, chapter, chapter_num, character) %>%
  count() %>%
  ungroup() %>%
  group_by(book, book_num, chapter, chapter_num) %>%
  mutate(percentage = n/sum(n))

```

# Visualize

Using your processed dataset, create your unique visualization.

```{r Visualize}

speaking %>% 
  filter(character %in% c("Aang", "Katara", "Sokka", "Toph", "Zuko")) %>%
  ggplot() +
  geom_col(mapping = aes(x = as.factor(chapter_num), y = percentage, fill = character)) +
  facet_wrap(~ book, ncol = 1) +
  theme_pander() +
  labs(title = "Proportion of Speaking Appearances for Major Characters in the Avatar Book Series",
      x = "Chapter",
      y = "Percentage") +
  scale_y_continuous(labels = scales::percent)

  
```
